'use client'

import { AnimatePresence, motion } from 'framer-motion'
import { useState } from 'react'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { ArrowRight, Check, ChevronRight, CircleAlert, Menu, ShieldCheck, X } from 'lucide-react'

const findings = [
  'Patient Wi-Fi shares network with patient records',
  'Workstations unencrypted, updates months behind',
  'No multi-factor authentication on email',
  'Backup untested, single copy, on-site only',
  'Nothing monitoring outside office hours',
  'No Security Risk Assessment on file',
]
const layers = [
  ['Network', 'Patient Wi-Fi physically cannot reach the practice server.', 'Ubiquiti UniFi gateway, switching, and access points segmented into three isolated zones.'],
  ['Identity & devices', 'Every device is known, encrypted, and protected.', 'Microsoft 365 Business Premium with Entra ID, enforced MFA, Intune, Defender, and email screening.'],
  ['24/7 detection', 'If something happens at 3 AM, someone is already on it.', 'Huntress managed detection and response backed by a human security operations centre.'],
  ['Backup & recovery', 'A dead server should not mean a dead day.', 'Axcient image-based backup every hour, offsite, covering your database and imaging folders.'],
  ['Documentation', 'Proof that your safeguards are working, ready when you need it.', 'Every patch, restore test, and training session logged in a monthly practice-health report.'],
]

const systems = [
  { name: 'Redundant internet', label: 'Dual ISP failover', tone: 'orange', icon: '↯' },
  { name: 'Firewall', label: 'Threat prevention', tone: 'red', icon: '▣' },
  { name: 'VLAN separation', label: 'Patient / clinical / guest', tone: 'teal', icon: '⌁' },
  { name: 'Dental systems', label: 'Charts + imaging', tone: 'blue', icon: '▤' },
  { name: '3–2–1 backup', label: 'Hourly recovery', tone: 'violet', icon: '◫' },
  { name: 'MFA + monitoring', label: 'Verified 24/7', tone: 'green', icon: '✓' },
]

function HeroCanvas({ step, setStep }: { step: number; setStep: (index: number) => void }) {
  const active = Math.min(step, systems.length - 1)
  return <div className="hero-canvas msp-hero-panel" aria-label="IT Square managed security coverage for a dental practice">
    <div className="msp-panel-header"><div><span className="panel-kicker">IT SQUARE / DENTAL PRACTICE COVERAGE</span><h2>One partner. Every safeguard.</h2><p>From the front desk to the cloud, we keep your practice available, secure, and audit-ready.</p></div><div className="hipaa-seal"><ShieldCheck size={18}/><span>HIPAA<br/><small>READY</small></span></div></div>
    <div className="coverage-list">{systems.map((system, index) => <button type="button" key={system.name} className={`coverage-row ${index === active ? 'is-active' : ''}`} onClick={() => setStep(index)}><span className={`coverage-icon ${system.tone}`}>{system.icon}</span><span className="coverage-copy"><b>{system.name}</b><small>{system.label}</small></span><span className="coverage-status">{index <= step ? 'PROTECTED' : 'COVERED NEXT'}</span><ChevronRight size={15}/></button>)}</div>
    <div className="msp-panel-footer"><span><i className="legend-dot secured"/>Managed, monitored, documented</span><strong>{step >= systems.length - 1 ? 'PRACTICE READY' : `${step + 1} / ${systems.length} CONTROLS ACTIVE`}</strong></div>
  </div>
}

export function MarketingHome() {
  const [step, setStep] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [layer, setLayer] = useState(0)
  const resolve = Math.min(step, 6)
  return <div className="site-shell">
    <header className="site-nav"><a className="brand" href="#top"><span className="brand-mark">IT</span><span>IT Square</span></a><nav className="desktop-nav"><a href="#stakes">Why it matters</a><a href="#stack">The stack</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><a className="nav-cta" href="#contact">Book assessment <ArrowRight size={15}/></a><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></header>
    {menuOpen && <div className="mobile-nav"><a href="#stakes" onClick={()=>setMenuOpen(false)}>Why it matters</a><a href="#stack" onClick={()=>setMenuOpen(false)}>The stack</a><a href="#pricing" onClick={()=>setMenuOpen(false)}>Pricing</a><a href="#faq" onClick={()=>setMenuOpen(false)}>FAQ</a></div>}
    <main id="top">
      <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> IT Square · Chicago</div><h1>IT for dental practices that <span>passes a HIPAA audit.</span></h1><p className="hero-lede">We split your network, lock every workstation, back up everything hourly, and document all of it. This is a typical install — watch it happen.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Book a free HIPAA assessment <ArrowRight size={16}/></a><button className="button button-ghost" onClick={()=>setStep(0)}>Replay install</button></div><p className="fine-print">90 minutes on site. Written report yours to keep, whether or not you hire us.</p><div className="stats-row"><div><strong>1 hour</strong><span>to be back seeing patients</span></div><div><strong>6</strong><span>average findings we open with</span></div><div><strong>100%</strong><span>of safeguards documented</span></div></div></div><div className="hero-visual"><HeroCanvas step={step} setStep={setStep}/><div className="scorecard"><div className="score-head"><div><span>OPEN FINDINGS</span><strong className={resolve===6?'resolved':''}>{6-resolve}</strong></div><span className={resolve===6?'status resolved':'status'}>{resolve===6?'SAFETY IN PLACE':'RISK DETECTED'}</span></div><div className="findings-list">{findings.map((finding,i)=><div className={i<resolve?'finding cleared':'finding'} key={finding}><span className="finding-icon">{i<resolve?<Check size={12}/>:<CircleAlert size={12}/>}</span><span>{finding}</span></div>)}</div></div><div className="step-controls" aria-label="Installation steps">{['Before','Network','Endpoints','Identity','Backup','Monitor','Ready'].map((label,i)=><button key={label} className={i===step?'active':''} aria-label={`Go to ${label} step`} onClick={()=>setStep(i)}><span>{String(i).padStart(2,'0')}</span>{label}</button>)}</div></div></section>
      <section id="stakes" className="stakes-section section"><div className="section-kicker">01 / THE STAKES</div><div className="section-heading"><h2>Most practices discover the gap <span>after</span> it costs them.</h2><p>Compliance is not a binder on a shelf. It is the quiet systems work that keeps a bad morning from becoming a public breach.</p></div><div className="stakes-grid">{[['The fine','HIPAA requires an annual Security Risk Assessment. Most practices have never had one done. Penalties scale with culpability, and “we didn’t know” is the most expensive answer.'],['The ransom','A practice with one untested backup and a flat network is one bad click from losing twelve years of charts and radiographs.'],['The lost day','When the server dies mid-morning, production stops. Ask any dentist what a full day off the schedule costs, then multiply by three.']].map(([title,copy],i)=><motion.article className="stake-card" key={title} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*0.1}}><span className="card-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></motion.article>)}</div><a className="text-link" href="https://ocrportal.hhs.gov/ocr/breach" target="_blank" rel="noreferrer">Real dental breaches are public record. <ArrowRight size={15}/></a></section>
      <section id="stack" className="stack-section section"><div className="section-kicker">02 / THE STACK</div><div className="section-heading"><h2>Safeguards you can <span>explain</span> to a patient.</h2><p>Technology should disappear into reliable operations. Here is exactly what protects your practice.</p></div><div className="stack-layout"><div className="layer-tabs">{layers.map(([name],i)=><button key={name} className={layer===i?'selected':''} onClick={()=>setLayer(i)}><span>0{i+1}</span>{name}<ChevronRight size={16}/></button>)}</div><AnimatePresence mode="wait"><motion.div className="layer-detail" key={layer} initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}}><div className="detail-icon"><ShieldCheck size={26}/></div><h3>{layers[layer][1]}</h3><p>{layers[layer][2]}</p><div className="detail-line"><Check size={15}/> Installed, monitored, and documented by IT Square.</div></motion.div></AnimatePresence></div></section>
      <section className="specialization section"><div className="special-copy"><div className="section-kicker">03 / DENTAL, SPECIFICALLY</div><h2>We know when your imaging stops talking to your chart.</h2><p>We run Open Dental in our own lab, and we know Dentrix, Eaglesoft, imaging bridges, and sensor drivers. We have already broken and fixed that exact thing.</p><a className="text-link" href="#contact">Talk to a dental IT team <ArrowRight size={15}/></a></div><div className="software-grid">{['Open Dental','Dentrix','Eaglesoft','Dexis','Apteryx'].map(name=><div key={name}>{name}</div>)}</div><div className="timeline"><div><strong>WEEK 1</strong><p>Audit and documentation · Agents deployed · Microsoft 365 secured · Passwords vaulted · Backups verified</p></div><div><strong>WEEK 2</strong><p>UniFi installed · Devices encrypted · Everything patched · Staff training launched · Baseline assessment delivered</p></div></div></section>
      <section id="pricing" className="pricing-section section"><div className="section-kicker">04 / SIMPLE PRICING</div><div className="section-heading"><h2>Clear coverage. No surprise tickets.</h2><p>Every plan starts with the same free assessment. We quote hardware and network installation separately.</p></div><div className="pricing-grid">{[['Essential','The reliable baseline','Monitoring, patching, helpdesk, backup, endpoint protection'],['Complete','Most practices choose this','Everything in Essential, plus the full security stack, Microsoft 365 management, training, reviews, and compliance documentation'],['Complete + Compliance','For practices that want the full record','Everything, plus annual assessments, written policies, incident response planning, and vendor BAA management']].map(([name,desc,copy],i)=><article className={`price-card ${i===1?'featured':''}`} key={name}>{i===1&&<span className="popular">MOST PRACTICES CHOOSE THIS</span>}<div className="price-title"><h3>{name}</h3><span>from $X<span>/user/month</span></span></div><p className="price-desc">{desc}</p><div className="price-copy"><Check size={15}/>{copy}</div><a href="#contact" className="price-link">Get a recommendation <ArrowRight size={15}/></a></article>)}</div><p className="pricing-note">Network installation and hardware quoted separately. Minimum engagement applies.</p></section>
      <section id="faq" className="faq-section section"><div className="section-heading"><div className="section-kicker">05 / FAQ</div><h2>The questions we hear first.</h2></div><Accordion type="single" collapsible className="faq-list">{['We already have an IT guy','What does the free assessment actually involve?','How fast can you recover our server?','Do you work with our practice management software?','What happens in the first 30 days?'].map((q,i)=><AccordionItem value={`item-${i}`} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{['That is okay. We can work alongside an internal IT person or replace the reactive parts of the job. The assessment will show you where the gaps are.','We spend 90 minutes on site reviewing network boundaries, endpoints, identity, backup, monitoring, and documentation. You keep the written report either way.','With a verified hourly image backup, we can boot a copy in the cloud and get you seeing patients within the hour.','Yes. We work with Open Dental, Dentrix, Eaglesoft, Dexis, Apteryx, and the bridges and drivers that connect them.','We audit, document, secure Microsoft 365, deploy agents, verify backups, and give you a baseline HIPAA assessment with clear next actions.'][i]}</AccordionContent></AccordionItem>)}</Accordion></section>
      <section id="contact" className="final-cta section"><div><div className="section-kicker">START WITH THE TRUTH</div><h2>Find out what&apos;s actually open in your practice.</h2><p>90 minutes on site. You keep the report.</p></div><a className="button button-primary" href="mailto:hello@itsquare.ai">Book a free HIPAA assessment <ArrowRight size={16}/></a></section>
    </main><footer className="site-footer"><div><a className="brand" href="#top"><span className="brand-mark">IT</span><span>IT Square</span></a><p>Managed IT & HIPAA compliance for dental practices.</p><small>© 2026 IT Square. Chicago, Illinois.</small></div><div className="footer-links"><div><strong>Services</strong><a href="#stack">Managed IT</a><a href="#stack">HIPAA compliance</a><a href="#stack">Backup & recovery</a></div><div><strong>Company</strong><a href="#contact">Contact</a><a href="#stakes">Why IT Square</a><a href="#faq">FAQ</a></div><div><strong>Legal</strong><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="mailto:hello@itsquare.ai">hello@itsquare.ai</a></div></div></footer>
  </div>
}

export default MarketingHome
